Implement Rails specific Clowder initialization
RedHatInsights/clowder-common-ruby pull request #32
Opened 2023-06-05 13:33 UTC by RoamingNoMaD

2023-06-06 07:51 UTC, skateman requested changes

2023-06-06 07:51 UTC, skateman commented on lib/clowder-common-ruby.rb
> +require 'clowder-common-ruby/engine'
This should not be the part of the base gem, only rails apps should load it.

2023-06-06 07:51 UTC, skateman commented on lib/clowder-common-ruby/config.rb
> +  class RailsConfig
This class should be in a separate file.

2023-06-07 07:29 UTC, skateman requested changes

2023-06-07 07:29 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +          key = "#{name}".underscore.to_sym
```suggestion
          key = name.underscore.to_sym
```

2023-06-07 07:29 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +      redis_config = rails_config.configure_redis
I am not sure about these allocations, you could definitely move these method calls to the right side of the hash values below. Also regarding the `rails_config`, what about not having it at all? Just move all methods as singleton methods, taking one argument (the first config) that they actually need.

```
  first_config = ClowderCommonRuby::Config.load
  clowder_config = {
    kafka: configure_kafka(first_config),
    ...
```

2023-06-07 07:29 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +        clowder_config_enabled: true,
I guess this can be omitted :thinking:

2023-06-07 07:29 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +        tlsCAPath: first_config.tlsCAPath
let's stick with snake case everywhere

2023-06-07 07:29 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +          clowder_config[key] = rails_config.configure_endpoint(endpoint.dig('service'))
I would not put them directly into the config, but under `:endpoints`

2023-06-07 07:29 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +      end
In general these two steps can be done during the hash creation above using `each_with_object` and you don't really need to adjust the hash afterwards:

```
def self.build_endpoints(endpoints)
  endpoints.&each_with_object({}) do |name, endpoint, obj| # not sure about the name-endpoint destruct here, maybe (name, endpoint), obj ... try it
    key = ...
    obj[key] = configure_endpoint(endpoint.dig('service'))
  end
end

def self.to_h
  clowder_config = {
     ...
     endpoints: build_endpoints(first_config&.dependency_endpoints),
     private_endpoints: build_endpoints(first_config&.private_dependency_endpoints)
     ...
  }
end
```

2023-06-07 13:01 UTC, skateman requested changes

2023-06-07 13:01 UTC, skateman commented on lib/clowder-common-ruby.rb
> +end
I don't think you really need these...

2023-06-07 14:16 UTC, skateman requested changes
Please drop the `first_config` word and just use `config` instead ... makes more sense.

2023-06-07 14:16 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +      kafka_config[:kafka_topics] = configure_kafka_topics(first_config)
```suggestion
      kafka_config[:kafka_topics] = kafka_topics(first_config)
```

2023-06-07 14:16 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +
No longer needed

2023-06-08 11:27 UTC, skateman requested changes
1. map -> hash 
2. `class << self` syntax
3. `to_hash` -> `to_h`

2023-06-08 11:27 UTC, skateman commented on config/initializers/test.rb
> +end
The name of this file should be something like `0-clowder-rails.rb`.

2023-06-08 11:27 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +    attr_reader :config
No longer used, no longer needed.

2023-06-08 11:27 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +    def self.configure_kafka(config)
When defining singleton methods, you can simply put them into a `class << self` block:
```ruby
class BlaBla
  class << self
    def to_h
       ...
    end

    # Strong feature of this syntax is the singleton-private methods.
    private

    def configure_kafka(config)
      ...
    end
  end
```

2023-06-08 11:27 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +    # Map for Kafka security settings
Kafka security settings hash

2023-06-08 11:27 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +    # Map for Kafka configuration
Kafka configuration hash

2023-06-08 11:27 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +        brokers: build_kafka_brokers(config) || '',
I would like to see a comment that explains why the `|| ''` is required.

2023-06-08 11:27 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +      return unless cacert.present?
Explain in a comment what this does.

2023-06-08 11:27 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +    def self.to_hash
```suggestion
    def self.to_h
```

2023-06-08 11:27 UTC, skateman commented on lib/clowder-common-ruby/rails_config.rb
> +    # Map for configuration of a single endpoint
Endpoint configuration hash

2023-06-14 11:31 UTC, skateman commented
Please add a description to the PR and link the counterpart, same for the counterpart...

2023-06-20 14:49 UTC, vkrizan approved these changes
Looks great Jany!

2023-06-23 04:54 UTC, skateman approved these changes
Great job! Just please adjust the remaining two things and this can be merged

2023-06-23 04:54 UTC, skateman commented on config/initializers/0_clowder_rails.rb
> +if ClowderCommonRuby::Config.clowder_enabled?
Let's make sure that `Settings` is available for the current context:
```suggestion
if ClowderCommonRuby::Config.clowder_enabled? && defined?(Settings)
```
cc @vkrizan so you sleep better :wink:

2023-06-23 04:54 UTC, skateman commented on lib/clowder-common-ruby/version.rb
> +  VERSION = '0.3.0'.freeze
You'll need a rebase here.

2023-06-23 07:44 UTC, merged